### PR TITLE
feat: authz middleware to accept both slug and uuid for system ns

### PR DESCRIPTION
**Pull request by ishanarya0**
authz middleware to accept both slug and uuid for system ns

### CODE REVIEW

**Comment by mabdh** [comment]
@ishanarya0 can you please add tests on this changes too?

**Comment by ishanarya0** [comment]
> @ishanarya0 can you please add tests on this changes too?
yes mas, this is WIP

**Comment by mabdh** [comment]
@ishanarya0 you could convert this as draft first

**Comment by ishanarya0** [comment]
> @ishanarya0 you could convert this as draft first

but i want to run tests and lint actions. I am not sure these run on draft PRs.
I'll request for a review once I am done.

**Review by mabdh — APPROVED** [review]

**Pull request merged**
